### ISSUE TITLE
dvbsklep.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13588] opened 2019-05-29 22:23 UTC
![Screenshot_20190530_002248](https://user-images.githubusercontent.com/36385327/58595496-25e21680-8271-11e9-9578-182c15a88398.png)

**Comment by krystian3w** [comment] 2019-06-02 16:38
duplicate of #13583

**Closed** 2019-06-02 18:58 UTC
Labels: social filters
