### ISSUE TITLE
nanoAdblocker/nanoDefender od dzisiaj to malware.

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#17360] opened 2020-10-16 08:13 UTC
1. `https://github.com/NanoAdblocker/NanoCore/issues/362#issuecomment-709428210`

2. `https://github.com/jspenguin2017/Snippets/issues/2`

3. https://www.reddit.com/r/chrome/comments/jc0vms/nanoadblocker_nanodefender_is_malware_now/

> tl;dr with a bit of context: The uBlock Origin developer, gorhill, looked into it. It seems to send information on every network connect, purpose is unknown. Nobody even knows really who those developers are. He suggests removing the extension as it can be considered malware now

**Comment by krystian3w** [comment] 2020-10-16 08:21
#17251

**Comment by krystian3w** [comment] 2020-10-16 08:21
Duplicate of #17251

**Closed** 2020-10-16 08:26 UTC
