### ISSUE TITLE
go.tvn24.pl

### ISSUE THREAD

**Issue by FadeMind** [MajkiIT/polish-ads-filter#13607] opened 2019-05-30 12:34 UTC
https://go.tvn24.pl/
![scr-1559219683-001](https://user-images.githubusercontent.com/9846948/58633196-14882100-82e8-11e9-9a11-f6c98d8356b5.png)

**Comment by krystian3w** [comment] 2019-05-30 13:06
Duplicate of #13597

**Closed** 2019-05-30 16:48 UTC
