### ISSUE TITLE
kobiety.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#19442] opened 2021-04-05 10:08 UTC
![Zrzut ekranu z 2021-04-05 12-07-59](https://user-images.githubusercontent.com/36385327/113563217-972a4780-9607-11eb-8159-a179967ce52b.png)

**Comment by krystian3w** [comment] 2021-04-05 20:42
Duplicate of https://github.com/AdguardTeam/AdguardFilters/issues/79388

**Closed** 2021-04-05 22:08 UTC
Labels: cookies
