### ISSUE TITLE
gazetka.be

### ISSUE THREAD

**Issue by mat41997** [MajkiIT/polish-ads-filter#4281] opened 2017-11-04 18:20 UTC
![2017-11-04 19_20_18- dzien swira opera_musical](https://user-images.githubusercontent.com/5884000/32408254-3b4b3ce8-c195-11e7-9a66-96a730fe784f.png)
http://gazetka.be/index.php?option=com_content&view=article&id=2164:dzie-wira-operamusical&catid=543:nr-165-padziernik-2017&Itemid=162

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.56
chrome 62.0.3202.75

**Comment by xxcriticxx** [comment] 2017-11-04 19:27
duplicate of https://github.com/MajkiIT/polish-ads-filter/issues/4228

**Closed** 2017-11-04 19:41 UTC
