### ISSUE TITLE
pai.info.pl

### ISSUE THREAD

**Issue by felix-22** [MajkiIT/polish-ads-filter#19451] opened 2021-04-05 11:47 UTC
`cookies`

![ss_166337_pai info pl_](https://user-images.githubusercontent.com/75935068/113570755-4588b980-9615-11eb-8f01-42ffe5d598b4.png)

**Comment by strict-block** [comment] 2021-04-05 21:01
Duplicate of #19436

**Closed** 2021-04-05 23:54 UTC
Labels: cookies
