### ISSUE TITLE
kpodr.pl

### ISSUE THREAD

**Issue by xMaap** [MajkiIT/polish-ads-filter#13425] opened 2019-05-19 10:38 UTC
![Screenshot_20190519_123808](https://user-images.githubusercontent.com/36385327/57981046-0528ee00-7a33-11e9-8fb6-a5ae19fb2280.png)

**Comment by krystian3w** [comment] 2019-05-19 18:49
Demencja? 

Duplicate #13408

**Comment by krystian3w** [comment] 2019-05-19 18:49
Duplicate of #13408

**Closed** 2019-05-19 19:19 UTC
Labels: social filters
